In [8]:
import pandas as pd

niveau_vie = pd.read_excel("C:/Users/gromm/Downloads/Niveau_de_vie.xlsx")

In [9]:
display(niveau_vie)

,1. Niveau de vie médian par département en 2017,Unnamed: 1,Unnamed: 2
0,NaN,NaN,en euros
1,Départements,NaN,Niveau de vie médian
2,01,Ain,22640
3,02,Aisne,19100
4,03,Allier,19750
...,...,...,...
101,974,La Réunion,15020
102,976,Mayotte,3120
103,France métropolitaine,NaN,21110
104,"Lecture : en Haute-Garonne, la moitié de la po...",NaN,NaN
105,"Source : Insee, Filosofi 2017 pour la France m...",NaN,NaN

In [ ]:
niveau_vie.columns = ["code_departement_2017", "departement_name", "euros"]
niveau_vie = niveau_vie.drop(niveau_vie.index[:2])
display(niveau_vie)

,code_departement_2017,departement_name,euros
2,01,Ain,22640
3,02,Aisne,19100
4,03,Allier,19750
5,04,Alpes-de-Haute-Provence,19940
6,05,Hautes-Alpes,20350
...,...,...,...
101,974,La Réunion,15020
102,976,Mayotte,3120
103,France métropolitaine,NaN,21110
104,"Lecture : en Haute-Garonne, la moitié de la po...",NaN,NaN
105,"Source : Insee, Filosofi 2017 pour la France m...",NaN,NaN

In [12]:
niveau_vie = niveau_vie.drop(niveau_vie.index[-2:])
display(niveau_vie)

     code_departement_2017         departement_name  euros
2                       01                      Ain  22640
3                       02                    Aisne  19100
4                       03                   Allier  19750
5                       04  Alpes-de-Haute-Provence  19940
6                       05             Hautes-Alpes  20350
..                     ...                      ...    ...
99                     972               Martinique  17580
100                    973                   Guyane  11040
101                    974               La Réunion  15020
102                    976                  Mayotte   3120
103  France métropolitaine                      NaN  21110

[102 rows x 3 columns]

In [14]:
niveau_vie = niveau_vie.fillna("All")
display(niveau_vie)

     code_departement_2017         departement_name  euros
2                       01                      Ain  22640
3                       02                    Aisne  19100
4                       03                   Allier  19750
5                       04  Alpes-de-Haute-Provence  19940
6                       05             Hautes-Alpes  20350
..                     ...                      ...    ...
99                     972               Martinique  17580
100                    973                   Guyane  11040
101                    974               La Réunion  15020
102                    976                  Mayotte   3120
103  France métropolitaine                      All  21110

[102 rows x 3 columns]

In [16]:
niveau_vie.to_csv("NiveauDeVieFrance.csv", index = False)