In [1]:
import pandas as pd

res_princ_2016 = pd.read_csv("C:/Users/gromm/Downloads/Proprio_VS_Locataires_ResidencesPrincipales2016.csv")

In [2]:
display(res_princ_2016)

,Résidences principales selon la taille des ménages et le statut d'occupation en 2016,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en milliers de logements
2,Au 1er janvier,1 pers.,2 pers.,3 pers.,4 pers.,5 pers.,6 pers. ou plus,Total
3,Propriétaire,"4,736","6,374","2,433","2,320",748,220,"16,830"
4,Locataire d'un logement vide non HLM,"3,122","1,809",841,533,205,97,"6,607"
5,Locataire d'un logement vide HLM,"1,689","1,066",655,475,267,158,"4,311"
6,Locataire d'un logement loué meublé,593,138,45,26,11,6,819
7,Logé gratuitement,315,168,89,69,21,9,670
8,Total,"10,454","9,555","4,064","3,422","1,253",490,"29,237"
9,Champ : France hors Mayotte.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Source : Insee, RP 2016 exploitation principale.",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
res_princ_2016 = res_princ_2016.drop(res_princ_2016.index[-2:])

In [5]:
res_princ_2016.columns = ["residences_principales", "1 pers.", "2. pers.", "3 pers.", "4 pers.", "5 pers.",	"6 pers. ou plus", "Total"]
res_princ_2016 = res_princ_2016.drop(res_princ_2016.index[:3])
display(res_princ_2016)

,residences_principales,1 pers.,2. pers.,3 pers.,4 pers.,5 pers.,6 pers. ou plus,Total
3,Propriétaire,"4,736","6,374","2,433","2,320",748,220,"16,830"
4,Locataire d'un logement vide non HLM,"3,122","1,809",841,533,205,97,"6,607"
5,Locataire d'un logement vide HLM,"1,689","1,066",655,475,267,158,"4,311"
6,Locataire d'un logement loué meublé,593,138,45,26,11,6,819
7,Logé gratuitement,315,168,89,69,21,9,670
8,Total,"10,454","9,555","4,064","3,422","1,253",490,"29,237"

In [7]:
res_princ_2016.to_csv("ResidencePrincipales2016.csv", index = False)