In [40]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\gromm\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [53]:
import pandas as pd

sdf = pd.read_csv("C:/Users/gromm/Downloads/SansAbris_toWork.csv")

display(sdf)

    Année  sans_abris
0    2018      3035.0
1    2019      3641.0
2    2020      3601.0
3    2021      2829.0
4    2022      2598.0
5    2023      3015.0
6    2024      3491.0
7    2025      3046.0
8    2026      3014.0
9    2027         NaN
10   2028         NaN
11   2029         NaN
12   2030         NaN
13   2031         NaN
14   2032         NaN
15   2033         NaN
16   2034         NaN
17   2035         NaN
18   2036         NaN

In [54]:
from sklearn.linear_model import LinearRegression

# données connues
train = sdf.dropna()

X = train[["Année"]]
y = train["sans_abris"]

model = LinearRegression()
model.fit(X, y)

# lignes à prédire
missing = sdf[sdf["sans_abris"].isna()]

pred = model.predict(missing[["Année"]])

sdf.loc[sdf["sans_abris"].isna(), "sans_abris"] = pred

display(sdf)

    Année   sans_abris
0    2018  3035.000000
1    2019  3641.000000
2    2020  3601.000000
3    2021  2829.000000
4    2022  2598.000000
5    2023  3015.000000
6    2024  3491.000000
7    2025  3046.000000
8    2026  3014.000000
9    2027  2982.527778
10   2028  2950.811111
11   2029  2919.094444
12   2030  2887.377778
13   2031  2855.661111
14   2032  2823.944444
15   2033  2792.227778
16   2034  2760.511111
17   2035  2728.794444
18   2036  2697.077778

In [55]:
# Export 

sdf.to_csv("SansAbris.csv", index = False)