In [46]:
import pandas as pd

In [47]:
df = pd.read_csv("/data/Projet_reconversion/Projet et cours Data Analyst/Cours Le Wagon/projet_crise_logement/données a traiter/Copie de Caracteristique_logement_mel_2022.csv", sep = ",")

/tmp/ipykernel_2700/1036814254.py:1: DtypeWarning: Columns (0: IRIS) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/data/Projet_reconversion/Projet et cours Data Analyst/Cours Le Wagon/projet_crise_logement/données a traiter/Copie de Caracteristique_logement_mel_2022.csv", sep = ",")

In [48]:
df.shape

(49827, 69)

Selection des colonnes à garder pour faire l'analyse des logements et leur ancienneté ainsi que de la vetustée == (ACHL = achèvement de la construction de l'immeuble,CATL = catégorie de logement, AEMMR = année d emménagement dans le logement regroupée,BATI = aspect du batiment, CATL = catégorie de logement,HLML = appartenance du logement a un organisme HLM,STOCD = statut d'occupation,SURF = superficie du logement, TYPL = type de logzmznt, TATCM = type d'activité de la personne de référence du ménage )

In [49]:
df.columns
columns = ["COMMUNE","ACHL","CATL","BATI","AEMMR","HLML","STOCD","SURF","TYPL","TACTM"]
df = df[columns]
df.head()

   COMMUNE   ACHL  CATL BATI  AEMMR HLML  STOCD SURF  TYPL TACTM
0    59100   C100     1    Z      9    2     10    7     1    21
1    59100    B12     1    Z      7    2     10    6     1    21
2    59100    A11     1    Z      8    2     10    5     1    11
3    59100    A11     1    Z      6    2     10    7     1    21
4    59100  C2020     1    Z      9    2     10    7     1    11

Remplacement des valeurs du tableau pour qu elles aient un sens

In [50]:
CATL_map = {
    "1": "Résidence principale",
    "2": "Logement occasionnel",
    "3": "Résidence secondaire",
    "4": "Logement vacant",
    "Z": "Hors logement ordinaire"
}
df["CATL"] = df["CATL"].astype(str)
df["CATL"] = df["CATL"].replace(CATL_map)
print(df["CATL"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,9,2,10,7,1,21
1,59100,B12,Résidence principale,Z,7,2,10,6,1,21
2,59100,A11,Résidence principale,Z,8,2,10,5,1,11
3,59100,A11,Résidence principale,Z,6,2,10,7,1,21
4,59100,C2020,Résidence principale,Z,9,2,10,7,1,11

In [51]:
AEMMR_map = {
    "0": "Inoccupé",
    "1": "1891-1899",
    "2": "1900-1919",
    "3": "1920-1939",
    "4": "1940-1959",
    "5": "1960-1969",
    "6": "1970-1979",
    "7": "1980-1989",
    "8": "1990-1999",
    "9": "Après 1999",
    "Z": "Hors logement ordinaire"
}
df["AEMMR"] = df["AEMMR"].astype(str)
df["AEMMR"] = df["AEMMR"].replace(AEMMR_map)
print(df["AEMMR"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,Après 1999,2,10,7,1,21
1,59100,B12,Résidence principale,Z,1980-1989,2,10,6,1,21
2,59100,A11,Résidence principale,Z,1990-1999,2,10,5,1,11
3,59100,A11,Résidence principale,Z,1970-1979,2,10,7,1,21
4,59100,C2020,Résidence principale,Z,Après 1999,2,10,7,1,11

In [52]:
HLML_map = {
    "1": "Logement HLM",
    "2": "Non HLM",
    "Y": "Hors résidence principale",
    "Z": "Hors logement ordinaire"
}
df["HLML"] = df["HLML"].astype(str)
df["HLML"] = df["HLML"].replace(HLML_map)
print(df["HLML"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,Après 1999,Non HLM,10,7,1,21
1,59100,B12,Résidence principale,Z,1980-1989,Non HLM,10,6,1,21
2,59100,A11,Résidence principale,Z,1990-1999,Non HLM,10,5,1,11
3,59100,A11,Résidence principale,Z,1970-1979,Non HLM,10,7,1,21
4,59100,C2020,Résidence principale,Z,Après 1999,Non HLM,10,7,1,11

In [53]:
STOCD_map = {
    "00": "Inoccupé",
    "10": "Propriétaire",
    "21": "Locataire logement vide non HLM",
    "22": "Locataire logement vide HLM",
    "23": "Locataire meublé",
    "30": "Logé gratuitement",
    "ZZ": "Hors logement ordinaire"
}
df["STOCD"] = df["STOCD"].astype(str)
df["STOCD"] = df["STOCD"].replace(STOCD_map)
print(df["STOCD"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,7,1,21
1,59100,B12,Résidence principale,Z,1980-1989,Non HLM,Propriétaire,6,1,21
2,59100,A11,Résidence principale,Z,1990-1999,Non HLM,Propriétaire,5,1,11
3,59100,A11,Résidence principale,Z,1970-1979,Non HLM,Propriétaire,7,1,21
4,59100,C2020,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,7,1,11

In [54]:
SURF_map = {
    "1": "<30 m²",
    "2": "30-40 m²",
    "3": "40-60 m²",
    "4": "60-80 m²",
    "5": "80-100 m²",
    "6": "100-120 m²",
    "7": "120 m² +",
    "Y": "Hors résidence principale",
    "Z": "Hors logement ordinaire"
}
df["SURF"] = df["SURF"].astype(str)
df["SURF"] = df["SURF"].replace(SURF_map)
print(df["SURF"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,120 m² +,1,21
1,59100,B12,Résidence principale,Z,1980-1989,Non HLM,Propriétaire,100-120 m²,1,21
2,59100,A11,Résidence principale,Z,1990-1999,Non HLM,Propriétaire,80-100 m²,1,11
3,59100,A11,Résidence principale,Z,1970-1979,Non HLM,Propriétaire,120 m² +,1,21
4,59100,C2020,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,120 m² +,1,11

In [55]:
TYPL_map = {
    "1": "Maison",
    "2": "Appartement",
    "3": "Logement foyer",
    "4": "Chambre hôtel",
    "5": "Habitation de fortune",
    "6": "Pièce indépendante",
    "Z": "Hors logement ordinaire"
}
df["TYPL"] = df["TYPL"].astype(str)
df["TYPL"] = df["TYPL"].replace(TYPL_map)
print(df["TYPL"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,21
1,59100,B12,Résidence principale,Z,1980-1989,Non HLM,Propriétaire,100-120 m²,Maison,21
2,59100,A11,Résidence principale,Z,1990-1999,Non HLM,Propriétaire,80-100 m²,Maison,11
3,59100,A11,Résidence principale,Z,1970-1979,Non HLM,Propriétaire,120 m² +,Maison,21
4,59100,C2020,Résidence principale,Z,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,11

In [56]:
BATI_map = {
    "1": "Habitations de fortune",
    "2": "Cases traditionnelles",
    "3": "Maisons ou immeubles en bois",
    "4": "Maisons ou immeubles en dur",
    "X": "Hors logement ordinaire (DOM et France métropolitaine)",
    "Y": "Hors résidence principale",
    "Z": "Logement ordinaire France métropolitaine"

}
df["BATI"] = df["BATI"].astype(str)
df["BATI"] = df["BATI"].replace(BATI_map)
print(df["BATI"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,C100,Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,21
1,59100,B12,Résidence principale,Logement ordinaire France métropolitaine,1980-1989,Non HLM,Propriétaire,100-120 m²,Maison,21
2,59100,A11,Résidence principale,Logement ordinaire France métropolitaine,1990-1999,Non HLM,Propriétaire,80-100 m²,Maison,11
3,59100,A11,Résidence principale,Logement ordinaire France métropolitaine,1970-1979,Non HLM,Propriétaire,120 m² +,Maison,21
4,59100,C2020,Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,11

In [57]:
ACHL_map = {
    "ZZZ": "Hors logement ordinaire",
    "A11": "Avant 1919",
    "A12": "1919 à 1945",
    "B11": "1946 à 1970",
    "B12": "1971 à 1990",
    "C100": "1991 à 2005",
    "C106": "2006",
    "C107": "2007",
    "C108": "2008",
    "C109": "2009",
    "C110": "2010",
    "C111": "2011",
    "C112": "2012",
    "C113": "2013",
    "C114": "2014",
    "C115": "2015",
    "C116": "2016",
    "C117": "2017",
    "C118": "2018",
    "C119": "2019",
    "C2020": "2020 (partiel)",
    "C2021": "2021 (partiel)",
    "C2022": "2022 (partiel)",
    "C2023": "2023 (partiel)",
    "C2024": "2024 (partiel)"
}
df["ACHL"] = df["ACHL"].astype(str)
df["ACHL"] = df["ACHL"].replace(ACHL_map)
print(df["ACHL"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,1991 à 2005,Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,21
1,59100,1971 à 1990,Résidence principale,Logement ordinaire France métropolitaine,1980-1989,Non HLM,Propriétaire,100-120 m²,Maison,21
2,59100,Avant 1919,Résidence principale,Logement ordinaire France métropolitaine,1990-1999,Non HLM,Propriétaire,80-100 m²,Maison,11
3,59100,Avant 1919,Résidence principale,Logement ordinaire France métropolitaine,1970-1979,Non HLM,Propriétaire,120 m² +,Maison,21
4,59100,2020 (partiel),Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,11

In [58]:
TACTM_map = {
    "11": "Actif occupé",
    "12": "Chômeur",
    "21": "Retraité ou préretraité",
    "22": "Élève ou étudiant",
    "23": "Moins de 14 ans",
    "24": "Au foyer",
    "25": "Autre inactif",
    "YY": "Hors résidence principale",
    "ZZ": "Hors logement ordinaire"
}
df["TACTM"] = df["TACTM"].astype(str)
df["TACTM"] = df["TACTM"].replace(TACTM_map)
print(df["TACTM"].dtype)
df.head()

str

,COMMUNE,ACHL,CATL,BATI,AEMMR,HLML,STOCD,SURF,TYPL,TACTM
0,59100,1991 à 2005,Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,Retraité ou préretraité
1,59100,1971 à 1990,Résidence principale,Logement ordinaire France métropolitaine,1980-1989,Non HLM,Propriétaire,100-120 m²,Maison,Retraité ou préretraité
2,59100,Avant 1919,Résidence principale,Logement ordinaire France métropolitaine,1990-1999,Non HLM,Propriétaire,80-100 m²,Maison,Actif occupé
3,59100,Avant 1919,Résidence principale,Logement ordinaire France métropolitaine,1970-1979,Non HLM,Propriétaire,120 m² +,Maison,Retraité ou préretraité
4,59100,2020 (partiel),Résidence principale,Logement ordinaire France métropolitaine,Après 1999,Non HLM,Propriétaire,120 m² +,Maison,Actif occupé