In [61]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/gromm/Downloads/Copie de logement_vacants_MEL.csv")

C:\Users\gromm\AppData\Local\Temp\ipykernel_17760\947727058.py:4: DtypeWarning: Columns (0: CODGEO_25, 1: EPCI_25, 2: DEP) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/gromm/Downloads/Copie de logement_vacants_MEL.csv")

In [62]:
# Keep only values for the North of France

df = df[df['CODGEO_25'].str.contains('59', na= False)]
df = df[df['CODGEO_25'].str.startswith("59")]
display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
21756,59001,Abancourt,s,s,s,12,s,s,14,s,...,s,s,15,s,200068500,Communauté d'agglomération de Cambrai,59,Nord,32,Hauts-de-France
21757,59002,Abscon,97,48,1415,128,51,1407,116,49,...,63,1373,126,52,200042190,Communauté d'agglomération de la Porte du Hainaut,59,Nord,32,Hauts-de-France
21758,59003,Aibes,15,s,s,23,s,s,19,s,...,s,s,13,s,200043396,Communauté d'agglomération Maubeuge Val de Sambre,59,Nord,32,Hauts-de-France
21759,59004,Aix-en-Pévèle,36,21,s,57,s,s,61,18,...,17,s,48,14,200041960,Communauté de communes Pévèle-Carembault,59,Nord,32,Hauts-de-France
21760,59005,Allennes-les-Marais,44,20,1376,64,s,1371,57,s,...,13,1340,79,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,s,624,42,11,...,14,607,38,15,200040954,Communauté de communes des Hauts de Flandre,59,Nord,32,Hauts-de-France
22399,59667,Zermezeele,s,s,104,s,s,101,s,0,...,s,s,s,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22400,59668,Zuydcoote,31,16,631,38,s,627,36,13,...,s,614,49,11,245900428,Communauté urbaine de Dunkerque,59,Nord,32,Hauts-de-France
22401,59669,Zuytpeene,20,s,s,18,s,s,18,s,...,s,s,18,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22402,59670,Don,13,s,564,26,s,561,17,s,...,s,538,46,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France

In [63]:
# Replaced "s" values by 0

df['pp_vacant_25'] = df['pp_vacant_25'].replace("s", 0)
df['pp_vacant_plus_2ans_25'] = df['pp_vacant_plus_2ans_25'].replace("s", 0)
df['pp_total_24'] = df['pp_total_24'].replace("s", 0)
df['pp_vacant_24'] = df['pp_vacant_24'].replace("s", 0)
df['pp_vacant_plus_2ans_24'] = df['pp_vacant_plus_2ans_24'].replace("s", 0)
df['pp_total_23'] = df['pp_total_23'].replace("s", 0)
df['pp_vacant_23'] = df['pp_vacant_23'].replace("s", 0)
df['pp_vacant_plus_2ans_23'] = df['pp_vacant_plus_2ans_23'].replace("s", 0)

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
21756,59001,Abancourt,0,0,0,12,0,0,14,0,...,s,s,15,s,200068500,Communauté d'agglomération de Cambrai,59,Nord,32,Hauts-de-France
21757,59002,Abscon,97,48,1415,128,51,1407,116,49,...,63,1373,126,52,200042190,Communauté d'agglomération de la Porte du Hainaut,59,Nord,32,Hauts-de-France
21758,59003,Aibes,15,0,0,23,0,0,19,0,...,s,s,13,s,200043396,Communauté d'agglomération Maubeuge Val de Sambre,59,Nord,32,Hauts-de-France
21759,59004,Aix-en-Pévèle,36,21,0,57,0,0,61,18,...,17,s,48,14,200041960,Communauté de communes Pévèle-Carembault,59,Nord,32,Hauts-de-France
21760,59005,Allennes-les-Marais,44,20,1376,64,0,1371,57,0,...,13,1340,79,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0,624,42,11,...,14,607,38,15,200040954,Communauté de communes des Hauts de Flandre,59,Nord,32,Hauts-de-France
22399,59667,Zermezeele,0,0,104,0,0,101,0,0,...,s,s,s,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22400,59668,Zuydcoote,31,16,631,38,0,627,36,13,...,s,614,49,11,245900428,Communauté urbaine de Dunkerque,59,Nord,32,Hauts-de-France
22401,59669,Zuytpeene,20,0,0,18,0,0,18,0,...,s,s,18,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22402,59670,Don,13,0,564,26,0,561,17,0,...,s,538,46,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France

In [64]:
# Remove useless columns

df.drop(columns= ["pp_total_20", 'pp_total_21','pp_total_22','pp_vacant_20', 'pp_vacant_21', 'pp_vacant_22',
                  'pp_vacant_plus_2ans_20', 'pp_vacant_plus_2ans_21', 'pp_vacant_plus_2ans_22', 'EPCI_25',
                  'LIB_EPCI_25', 'DEP', 'LIB_DEP', 'REG', 'LIB_REG'], inplace = True)

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23
21756,59001,Abancourt,0,0,0,12,0,0,14,0
21757,59002,Abscon,97,48,1415,128,51,1407,116,49
21758,59003,Aibes,15,0,0,23,0,0,19,0
21759,59004,Aix-en-Pévèle,36,21,0,57,0,0,61,18
21760,59005,Allennes-les-Marais,44,20,1376,64,0,1371,57,0
...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0,624,42,11
22399,59667,Zermezeele,0,0,104,0,0,101,0,0
22400,59668,Zuydcoote,31,16,631,38,0,627,36,13
22401,59669,Zuytpeene,20,0,0,18,0,0,18,0
22402,59670,Don,13,0,564,26,0,561,17,0

In [66]:
# Set types of columns values to int

df.iloc[:, 2:11] = df.iloc[:, 2:11].astype(int)

# Replace 0 by NaN values then fill NaN with median value

df[df.columns[2:10]] = df[df.columns[2:10]].replace(0, np.nan).fillna(df[df.columns[2:10]].median())

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23
21756,59001,Abancourt,28,11,494,12,0.0,492,14,11
21757,59002,Abscon,97,48,1415,128,51,1407,116,49
21758,59003,Aibes,15,11,494,23,0.0,492,19,11
21759,59004,Aix-en-Pévèle,36,21,494,57,0.0,492,61,18
21760,59005,Allennes-les-Marais,44,20,1376,64,0.0,1371,57,11
...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0.0,624,42,11
22399,59667,Zermezeele,28,11,104,39,0.0,101,37,11
22400,59668,Zuydcoote,31,16,631,38,0.0,627,36,13
22401,59669,Zuytpeene,20,11,494,18,0.0,492,18,11
22402,59670,Don,13,11,564,26,0.0,561,17,11

In [ ]:
# Export

df.to_csv('LogementsVacants_MEL.csv', index = False)