In [10]:
import pandas as pd

logementsSociaux = pd.read_csv("C:/Users/gromm/Downloads/Copie de LogementsSociaux.csv")
display(logementsSociaux)

     code_geo              lib_geo  année  nb_rpls
0       59001            Abancourt   2023      NaN
1       59002               Abscon   2023    573.0
2       59003                Aibes   2023      NaN
3       59004        Aix-en-Pévèle   2023      NaN
4       59005  Allennes-les-Marais   2023    135.0
..        ...                  ...    ...      ...
642     59666         Zegerscappel   2023     30.0
643     59667           Zermezeele   2023      NaN
644     59668            Zuydcoote   2023    115.0
645     59669            Zuytpeene   2023      NaN
646     59670                  Don   2023     86.0

[647 rows x 4 columns]

In [11]:
# Filled NaN values with the median value of all cities in the North of France

logementsSociaux = logementsSociaux.fillna(logementsSociaux['nb_rpls'].median())
display(logementsSociaux)

     code_geo              lib_geo  année  nb_rpls
0       59001            Abancourt   2023     64.0
1       59002               Abscon   2023    573.0
2       59003                Aibes   2023     64.0
3       59004        Aix-en-Pévèle   2023     64.0
4       59005  Allennes-les-Marais   2023    135.0
..        ...                  ...    ...      ...
642     59666         Zegerscappel   2023     30.0
643     59667           Zermezeele   2023     64.0
644     59668            Zuydcoote   2023    115.0
645     59669            Zuytpeene   2023     64.0
646     59670                  Don   2023     86.0

[647 rows x 4 columns]

In [12]:
# Export

logementsSociaux.to_csv("LogementsSociaux.csv", index = False)