In [117]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/gromm/Downloads/Copie de logement_vacants_MEL.csv")

C:\Users\gromm\AppData\Local\Temp\ipykernel_1768\947727058.py:4: DtypeWarning: Columns (0: CODGEO_25, 1: EPCI_25, 2: DEP) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("C:/Users/gromm/Downloads/Copie de logement_vacants_MEL.csv")

In [118]:
# Keep only values for the North of France

df = df[df['CODGEO_25'].str.contains('59', na= False)]
df = df[df['CODGEO_25'].str.startswith("59")]
display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
21756,59001,Abancourt,s,s,s,12,s,s,14,s,...,s,s,15,s,200068500,Communauté d'agglomération de Cambrai,59,Nord,32,Hauts-de-France
21757,59002,Abscon,97,48,1415,128,51,1407,116,49,...,63,1373,126,52,200042190,Communauté d'agglomération de la Porte du Hainaut,59,Nord,32,Hauts-de-France
21758,59003,Aibes,15,s,s,23,s,s,19,s,...,s,s,13,s,200043396,Communauté d'agglomération Maubeuge Val de Sambre,59,Nord,32,Hauts-de-France
21759,59004,Aix-en-Pévèle,36,21,s,57,s,s,61,18,...,17,s,48,14,200041960,Communauté de communes Pévèle-Carembault,59,Nord,32,Hauts-de-France
21760,59005,Allennes-les-Marais,44,20,1376,64,s,1371,57,s,...,13,1340,79,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,s,624,42,11,...,14,607,38,15,200040954,Communauté de communes des Hauts de Flandre,59,Nord,32,Hauts-de-France
22399,59667,Zermezeele,s,s,104,s,s,101,s,0,...,s,s,s,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22400,59668,Zuydcoote,31,16,631,38,s,627,36,13,...,s,614,49,11,245900428,Communauté urbaine de Dunkerque,59,Nord,32,Hauts-de-France
22401,59669,Zuytpeene,20,s,s,18,s,s,18,s,...,s,s,18,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22402,59670,Don,13,s,564,26,s,561,17,s,...,s,538,46,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France

In [119]:
# Replaced "s" values by 0

df['pp_vacant_25'] = df['pp_vacant_25'].replace("s", 0)
df['pp_vacant_plus_2ans_25'] = df['pp_vacant_plus_2ans_25'].replace("s", 0)
df['pp_total_24'] = df['pp_total_24'].replace("s", 0)
df['pp_vacant_24'] = df['pp_vacant_24'].replace("s", 0)
df['pp_vacant_plus_2ans_24'] = df['pp_vacant_plus_2ans_24'].replace("s", 0)
df['pp_total_23'] = df['pp_total_23'].replace("s", 0)
df['pp_vacant_23'] = df['pp_vacant_23'].replace("s", 0)
df['pp_vacant_plus_2ans_23'] = df['pp_vacant_plus_2ans_23'].replace("s", 0)

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23,...,pp_vacant_plus_2ans_21,pp_total_20,pp_vacant_20,pp_vacant_plus_2ans_20,EPCI_25,LIB_EPCI_25,DEP,LIB_DEP,REG,LIB_REG
21756,59001,Abancourt,0,0,0,12,0,0,14,0,...,s,s,15,s,200068500,Communauté d'agglomération de Cambrai,59,Nord,32,Hauts-de-France
21757,59002,Abscon,97,48,1415,128,51,1407,116,49,...,63,1373,126,52,200042190,Communauté d'agglomération de la Porte du Hainaut,59,Nord,32,Hauts-de-France
21758,59003,Aibes,15,0,0,23,0,0,19,0,...,s,s,13,s,200043396,Communauté d'agglomération Maubeuge Val de Sambre,59,Nord,32,Hauts-de-France
21759,59004,Aix-en-Pévèle,36,21,0,57,0,0,61,18,...,17,s,48,14,200041960,Communauté de communes Pévèle-Carembault,59,Nord,32,Hauts-de-France
21760,59005,Allennes-les-Marais,44,20,1376,64,0,1371,57,0,...,13,1340,79,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0,624,42,11,...,14,607,38,15,200040954,Communauté de communes des Hauts de Flandre,59,Nord,32,Hauts-de-France
22399,59667,Zermezeele,0,0,104,0,0,101,0,0,...,s,s,s,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22400,59668,Zuydcoote,31,16,631,38,0,627,36,13,...,s,614,49,11,245900428,Communauté urbaine de Dunkerque,59,Nord,32,Hauts-de-France
22401,59669,Zuytpeene,20,0,0,18,0,0,18,0,...,s,s,18,s,200040947,Communauté d'agglomération Cœur de Flandre,59,Nord,32,Hauts-de-France
22402,59670,Don,13,0,564,26,0,561,17,0,...,s,538,46,s,200093201,Métropole Européenne de Lille,59,Nord,32,Hauts-de-France

In [120]:
# Remove useless columns

df.drop(columns= ["pp_total_20", 'pp_total_21','pp_total_22','pp_vacant_20', 'pp_vacant_21', 'pp_vacant_22',
                  'pp_vacant_plus_2ans_20', 'pp_vacant_plus_2ans_21', 'pp_vacant_plus_2ans_22', 'EPCI_25',
                  'LIB_EPCI_25', 'DEP', 'LIB_DEP', 'REG', 'LIB_REG'], inplace = True)

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23
21756,59001,Abancourt,0,0,0,12,0,0,14,0
21757,59002,Abscon,97,48,1415,128,51,1407,116,49
21758,59003,Aibes,15,0,0,23,0,0,19,0
21759,59004,Aix-en-Pévèle,36,21,0,57,0,0,61,18
21760,59005,Allennes-les-Marais,44,20,1376,64,0,1371,57,0
...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0,624,42,11
22399,59667,Zermezeele,0,0,104,0,0,101,0,0
22400,59668,Zuydcoote,31,16,631,38,0,627,36,13
22401,59669,Zuytpeene,20,0,0,18,0,0,18,0
22402,59670,Don,13,0,564,26,0,561,17,0

In [121]:
# Set types of columns values to int

df.iloc[:, 2:11] = df.iloc[:, 2:11].astype(int)

# Replace 0 by NaN values then fill NaN with median value

df[df.columns[2:10]] = df[df.columns[2:10]].replace(0, np.nan).fillna(df[df.columns[2:10]].median())

display(df)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23
21756,59001,Abancourt,28.0,11.0,494.0,12,0.0,492.0,14,11.0
21757,59002,Abscon,97,48,1415,128,51,1407,116,49
21758,59003,Aibes,15,11.0,494.0,23,0.0,492.0,19,11.0
21759,59004,Aix-en-Pévèle,36,21,494.0,57,0.0,492.0,61,18
21760,59005,Allennes-les-Marais,44,20,1376,64,0.0,1371,57,11.0
...,...,...,...,...,...,...,...,...,...,...
22398,59666,Zegerscappel,34,18,633,52,0.0,624,42,11
22399,59667,Zermezeele,28.0,11.0,104,39.0,0.0,101,37.0,11.0
22400,59668,Zuydcoote,31,16,631,38,0.0,627,36,13
22401,59669,Zuytpeene,20,11.0,494.0,18,0.0,492.0,18,11.0
22402,59670,Don,13,11.0,564,26,0.0,561,17,11.0

In [122]:
codes = pd.read_csv("C:/Users/gromm/Downloads/CodePostaux.csv")
display(codes)

,code_commune_INSEE,nom_commune_postal,code_postal,libelle_acheminement,ligne_5,latitude,longitude,code_commune,article,nom_commune,nom_commune_complet,code_departement,nom_departement,code_region,nom_region
0,59011,ANNOEULLIN,59112,ANNOEULLIN,NaN,50.526515,2.927536,11.0,NaN,Annœullin,Annœullin,59,Nord,32.0,Hauts-de-France
1,59013,ANSTAING,59152,ANSTAING,NaN,50.603524,3.189202,13.0,NaN,Anstaing,Anstaing,59,Nord,32.0,Hauts-de-France
2,59017,ARMENTIERES,59280,ARMENTIERES,NaN,50.691380,2.879716,17.0,NaN,Armentières,Armentières,59,Nord,32.0,Hauts-de-France
3,59017,ARMENTIERES,59280,ARMENTIERES,LE BIZET,50.691380,2.879716,17.0,NaN,Armentières,Armentières,59,Nord,32.0,Hauts-de-France
4,59025,AUBERS,59249,AUBERS,NaN,50.596051,2.819954,25.0,NaN,Aubers,Aubers,59,Nord,32.0,Hauts-de-France
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,59653,WAVRIN,59136,WAVRIN,NaN,50.572622,2.933372,653.0,NaN,Wavrin,Wavrin,59,Nord,32.0,Hauts-de-France
91,59656,WERVICQ SUD,59117,WERVICQ SUD,NaN,50.762046,3.050898,656.0,NaN,Wervicq-Sud,Wervicq-Sud,59,Nord,32.0,Hauts-de-France
92,59658,WICRES,59134,WICRES,NaN,50.569420,2.868590,658.0,NaN,Wicres,Wicres,59,Nord,32.0,Hauts-de-France
93,59660,WILLEMS,59780,WILLEMS,NaN,50.630607,3.229170,660.0,NaN,Willems,Willems,59,Nord,32.0,Hauts-de-France
94,59670,DON,59272,DON,NaN,50.544049,2.915578,670.0,NaN,Don,Don,59,Nord,32.0,Hauts-de-France

In [123]:
# We only need codes

codes_out = codes[['code_commune_INSEE']]

In [126]:
codes_out.rename(columns ={'code_commune_INSEE': 'CODGEO_25'}, inplace=True)

df['CODGEO_25'] = df['CODGEO_25'].astype(int)

df_logements_vacants = pd.merge(codes_out, df, how = 'inner', on = 'CODGEO_25')

display(df_logements_vacants)

,CODGEO_25,LIBGEO_25,pp_vacant_25,pp_vacant_plus_2ans_25,pp_total_24,pp_vacant_24,pp_vacant_plus_2ans_24,pp_total_23,pp_vacant_23,pp_vacant_plus_2ans_23
0,59011,Annœullin,139,68,3788,245,56,3771,192,66
1,59013,Anstaing,21,11.0,598,29,0.0,597,29,11.0
2,59017,Armentières,845,407,10345,1444,338,10103,1375,320
3,59017,Armentières,845,407,10345,1444,338,10103,1375,320
4,59025,Aubers,22,11.0,752,41,0.0,735,42,11.0
...,...,...,...,...,...,...,...,...,...,...
90,59653,Wavrin,87,41,2825,131,27,2814,165,23
91,59656,Wervicq-Sud,54,30,1696,78,20,1667,78,20
92,59658,Wicres,28.0,11.0,206,13,0.0,203,11,11.0
93,59660,Willems,37,11,1014,56,0.0,1008,37,11.0
94,59670,Don,13,11.0,564,26,0.0,561,17,11.0

In [128]:
# Export

df_logements_vacants.to_csv('LogementsVacants_MEL_Exploitable.csv', index = False)