In [6]:
import pandas as pd

res_princ = pd.read_csv("C:/Users/gromm/Downloads/Proprio_VS_Locataire_ResidencesPrincipales.csv")

In [ ]:
# Removed the 3 first rows

res_princ = res_princ.drop(res_princ.index[:3])
display(res_princ)

,Statut d’occupation des résidences principales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
3,Propriétaires,55.9,56.6,57.2,57.5,57.7,57.7,57.7
4,Non accédants,34.9,36.4,37.7,37.8,37.9,37.8,37.7
5,Accédants,21.0,20.2,19.6,19.7,19.8,19.9,20.0
6,Locataires,39.7,39.4,39.3,39.4,39.5,39.8,39.9
7,Bailleurs publics,17.9,17.7,17.5,17.3,17.2,17.1,17.0
8,Bailleurs privés,21.8,21.7,21.8,22.1,22.3,22.7,22.9
9,Autres statuts1,4.4,4.0,3.5,3.1,2.8,2.5,2.4
10,Total des résidences principales (en milliers),"24,973","26,016","26,993","27,786","28,516","29,237","29,916"
11,p : données provisoires.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,r : données révisées.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1. Regroupent essentiellement les ménages logé...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Champ : France hors Mayotte.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"Sources : Insee-SDES, estimation annuelle du p...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Removed the 5 last rows

res_princ = res_princ.drop(res_princ.index[-5:])
display(res_princ)

,Statut d’occupation des résidences principales,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
3,Propriétaires,55.9,56.6,57.2,57.5,57.7,57.7,57.7
4,Non accédants,34.9,36.4,37.7,37.8,37.9,37.8,37.7
5,Accédants,21.0,20.2,19.6,19.7,19.8,19.9,20.0
6,Locataires,39.7,39.4,39.3,39.4,39.5,39.8,39.9
7,Bailleurs publics,17.9,17.7,17.5,17.3,17.2,17.1,17.0
8,Bailleurs privés,21.8,21.7,21.8,22.1,22.3,22.7,22.9
9,Autres statuts1,4.4,4.0,3.5,3.1,2.8,2.5,2.4
10,Total des résidences principales (en milliers),"24,973","26,016","26,993","27,786","28,516","29,237","29,916"

In [ ]:
# Renamed columns

res_princ.columns = ['statut_occupation', '2001', '2004', '2007', '2010', '2013', '2016', '2019']

In [ ]:
# Export

res_princ.to_csv("ResidencesPrincipales_clean.csv", index = False)