In [1]:
import pandas as pd

repartition_statut_occupation = pd.read_csv("C:/Users/gromm/Downloads/Parc de logements.xlsx - Figure 5.csv")
display(repartition_statut_occupation)

,Figure 5 – Répartition des résidences principales selon le statut d'occupation,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en %
1,Année,Ensemble des propriétaires,Propriétaires sans charge de remboursement,Accédants à la propriété,Ensemble des locataires,Bailleurs publics,Bailleurs privés,Logés gratuitement
2,1982r,"50,6","27,6","23,0","41,6","14,8","26,7","7,8"
3,1983r,"51,3","27,8","23,5","41,2","15,1","26,2","7,5"
4,1984r,"51,9","28,0","23,9","40,9","15,3","25,6","7,2"
5,1985r,"52,6","28,2","24,3","40,6","15,5","25,1","6,8"
6,1986r,"53,2","28,4","24,8","40,3","15,7","24,6","6,5"
7,1987r,"53,8","28,7","25,2","40,0","15,9","24,1","6,2"
8,1988r,"54,4","28,8","25,6","39,7","16,1","23,6","5,9"
9,1989r,"54,9","29,0","26,0","39,5","16,4","23,1","5,5"
10,1990r,"55,0","29,6","25,3","39,6","16,7","22,9","5,4"
11,1991r,"54,9","30,3","24,7","39,7","17,1","22,6","5,4"
12,1992r,"54,9","30,9","24,0","39,8","17,4","22,4","5,3"
13,1993r,"54,9","31,5","23,3","39,9","17,8","22,2","5,2"
14,1994r,"54,9","31,9","23,0","40,1","18,0","22,1","5,0"
15,1995r,"54,9","32,3","22,6","40,3","18,3","22,1","4,7"
16,1996r,"55,0","32,7","22,3","40,5","18,5","22,0","4,5"
17,1997r,"55,0","33,1","22,0","40,7","18,7","21,9","4,3"
18,1998r,"55,2","33,5","21,7","40,6","18,7","22,0","4,2"
19,1999r,"55,5","34,0","21,5","40,5","18,5","22,0","4,0"
20,2000r,"55,7","34,4","21,3","40,4","18,4","22,0","3,9"
21,2001r,"55,9","34,9","21,0","40,4","18,3","22,0","3,7"
22,2002r,"56,1","35,3","20,8","40,3","18,2","22,0","3,6"
23,2003r,"56,4","35,9","20,5","40,2","18,2","22,0","3,4"
24,2004r,"56,7","36,5","20,2","40,1","18,1","22,0","3,3"
25,2005r,"56,9","37,1","19,9","40,0","18,0","21,9","3,1"
26,2006r,"57,2","37,6","19,5","39,9","18,0","21,9","3,0"
27,2007r,"57,4","37,8","19,6","39,8","17,9","21,9","2,9"
28,2008r,"57,5","37,9","19,6","39,7","17,8","21,9","2,8"
29,2009r,"57,6","38,0","19,6","39,7","17,7","22,0","2,7"
30,2010r,"57,7","38,0","19,7","39,7","17,6","22,1","2,6"
31,2011r,"57,7","38,0","19,7","39,8","17,6","22,2","2,5"
32,2012r,"57,7","38,0","19,7","39,8","17,5","22,3","2,5"
33,2013r,"57,7","37,9","19,8","39,9","17,5","22,4","2,4"
34,2014r,"57,6","37,8","19,8","40,0","17,5","22,5","2,4"
35,2015r,"57,6","37,5","20,1","40,1","17,5","22,6","2,3"
36,2016r,"57,6","37,3","20,3","40,1","17,5","22,6","2,3"
37,2017r,"57,5","36,9","20,6","40,2","17,5","22,7","2,3"
38,2018r,"57,5","36,7","20,8","40,3","17,6","22,7","2,2"
39,2019r,"57,5","36,5","21,1","40,2","17,5","22,7","2,2"
40,2020r,"57,5","36,2","21,3","40,3","17,6","22,7","2,2"
41,2021r,"57,5","36,0","21,6","40,3","17,6","22,7","2,2"
42,2022r,"57,5","35,7","21,8","40,3","17,6","22,7","2,2"
43,2023p,"57,5","35,4","22,1","40,3","17,6","22,7","2,2"
44,2024p,"57,4","35,1","22,3","40,3","17,6","22,7","2,2"
45,2025p,"57,4","34,9","22,6","40,4","17,6","22,8","2,2"
46,p : données provisoires ; r : données révisées.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Notes :\n– Les données de 1982 à 2022 sont rév...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,"Lecture : En 2025, 57,4 % des ménages sont pro...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,"Champ : France hors Mayotte, résidences princi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,Sources : Insee ; ministère de la Transition é...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Renamed columns

repartition_statut_occupation.columns = ["annee", "ensemble_proprio", "proprio_sans_remboursement", 
                                         "proprio_accedant_propriete", "ensemble_locataires", "bailleurs_publics", "bailleurs_prives",
                                         "loges_gratuitement"]

# Removed the 2 first and the 5 last rows

repartition_statut_occupation = repartition_statut_occupation.drop(repartition_statut_occupation.index[:2])
repartition_statut_occupation = repartition_statut_occupation.drop(repartition_statut_occupation.index[-5:])

display(repartition_statut_occupation)

,annee,ensemble_proprio,proprio_sans_remboursement,proprio_accedant_propriete,ensemble_locataires,bailleurs_publics,bailleurs_prives,loges_gratuitement
2,1982r,"50,6","27,6","23,0","41,6","14,8","26,7","7,8"
3,1983r,"51,3","27,8","23,5","41,2","15,1","26,2","7,5"
4,1984r,"51,9","28,0","23,9","40,9","15,3","25,6","7,2"
5,1985r,"52,6","28,2","24,3","40,6","15,5","25,1","6,8"
6,1986r,"53,2","28,4","24,8","40,3","15,7","24,6","6,5"
7,1987r,"53,8","28,7","25,2","40,0","15,9","24,1","6,2"
8,1988r,"54,4","28,8","25,6","39,7","16,1","23,6","5,9"
9,1989r,"54,9","29,0","26,0","39,5","16,4","23,1","5,5"
10,1990r,"55,0","29,6","25,3","39,6","16,7","22,9","5,4"
11,1991r,"54,9","30,3","24,7","39,7","17,1","22,6","5,4"
12,1992r,"54,9","30,9","24,0","39,8","17,4","22,4","5,3"
13,1993r,"54,9","31,5","23,3","39,9","17,8","22,2","5,2"
14,1994r,"54,9","31,9","23,0","40,1","18,0","22,1","5,0"
15,1995r,"54,9","32,3","22,6","40,3","18,3","22,1","4,7"
16,1996r,"55,0","32,7","22,3","40,5","18,5","22,0","4,5"
17,1997r,"55,0","33,1","22,0","40,7","18,7","21,9","4,3"
18,1998r,"55,2","33,5","21,7","40,6","18,7","22,0","4,2"
19,1999r,"55,5","34,0","21,5","40,5","18,5","22,0","4,0"
20,2000r,"55,7","34,4","21,3","40,4","18,4","22,0","3,9"
21,2001r,"55,9","34,9","21,0","40,4","18,3","22,0","3,7"
22,2002r,"56,1","35,3","20,8","40,3","18,2","22,0","3,6"
23,2003r,"56,4","35,9","20,5","40,2","18,2","22,0","3,4"
24,2004r,"56,7","36,5","20,2","40,1","18,1","22,0","3,3"
25,2005r,"56,9","37,1","19,9","40,0","18,0","21,9","3,1"
26,2006r,"57,2","37,6","19,5","39,9","18,0","21,9","3,0"
27,2007r,"57,4","37,8","19,6","39,8","17,9","21,9","2,9"
28,2008r,"57,5","37,9","19,6","39,7","17,8","21,9","2,8"
29,2009r,"57,6","38,0","19,6","39,7","17,7","22,0","2,7"
30,2010r,"57,7","38,0","19,7","39,7","17,6","22,1","2,6"
31,2011r,"57,7","38,0","19,7","39,8","17,6","22,2","2,5"
32,2012r,"57,7","38,0","19,7","39,8","17,5","22,3","2,5"
33,2013r,"57,7","37,9","19,8","39,9","17,5","22,4","2,4"
34,2014r,"57,6","37,8","19,8","40,0","17,5","22,5","2,4"
35,2015r,"57,6","37,5","20,1","40,1","17,5","22,6","2,3"
36,2016r,"57,6","37,3","20,3","40,1","17,5","22,6","2,3"
37,2017r,"57,5","36,9","20,6","40,2","17,5","22,7","2,3"
38,2018r,"57,5","36,7","20,8","40,3","17,6","22,7","2,2"
39,2019r,"57,5","36,5","21,1","40,2","17,5","22,7","2,2"
40,2020r,"57,5","36,2","21,3","40,3","17,6","22,7","2,2"
41,2021r,"57,5","36,0","21,6","40,3","17,6","22,7","2,2"
42,2022r,"57,5","35,7","21,8","40,3","17,6","22,7","2,2"
43,2023p,"57,5","35,4","22,1","40,3","17,6","22,7","2,2"
44,2024p,"57,4","35,1","22,3","40,3","17,6","22,7","2,2"
45,2025p,"57,4","34,9","22,6","40,4","17,6","22,8","2,2"

In [ ]:
# Removed "r" and "p" from years

repartition_statut_occupation['annee'] = repartition_statut_occupation['annee'].str.replace("r", '')
repartition_statut_occupation['annee'] = repartition_statut_occupation['annee'].str.replace("p", '')
display(repartition_statut_occupation)

,annee,ensemble_proprio,proprio_sans_remboursement,proprio_accedant_propriete,ensemble_locataires,bailleurs_publics,bailleurs_prives,loges_gratuitement
2,1982,"50,6","27,6","23,0","41,6","14,8","26,7","7,8"
3,1983,"51,3","27,8","23,5","41,2","15,1","26,2","7,5"
4,1984,"51,9","28,0","23,9","40,9","15,3","25,6","7,2"
5,1985,"52,6","28,2","24,3","40,6","15,5","25,1","6,8"
6,1986,"53,2","28,4","24,8","40,3","15,7","24,6","6,5"
7,1987,"53,8","28,7","25,2","40,0","15,9","24,1","6,2"
8,1988,"54,4","28,8","25,6","39,7","16,1","23,6","5,9"
9,1989,"54,9","29,0","26,0","39,5","16,4","23,1","5,5"
10,1990,"55,0","29,6","25,3","39,6","16,7","22,9","5,4"
11,1991,"54,9","30,3","24,7","39,7","17,1","22,6","5,4"
12,1992,"54,9","30,9","24,0","39,8","17,4","22,4","5,3"
13,1993,"54,9","31,5","23,3","39,9","17,8","22,2","5,2"
14,1994,"54,9","31,9","23,0","40,1","18,0","22,1","5,0"
15,1995,"54,9","32,3","22,6","40,3","18,3","22,1","4,7"
16,1996,"55,0","32,7","22,3","40,5","18,5","22,0","4,5"
17,1997,"55,0","33,1","22,0","40,7","18,7","21,9","4,3"
18,1998,"55,2","33,5","21,7","40,6","18,7","22,0","4,2"
19,1999,"55,5","34,0","21,5","40,5","18,5","22,0","4,0"
20,2000,"55,7","34,4","21,3","40,4","18,4","22,0","3,9"
21,2001,"55,9","34,9","21,0","40,4","18,3","22,0","3,7"
22,2002,"56,1","35,3","20,8","40,3","18,2","22,0","3,6"
23,2003,"56,4","35,9","20,5","40,2","18,2","22,0","3,4"
24,2004,"56,7","36,5","20,2","40,1","18,1","22,0","3,3"
25,2005,"56,9","37,1","19,9","40,0","18,0","21,9","3,1"
26,2006,"57,2","37,6","19,5","39,9","18,0","21,9","3,0"
27,2007,"57,4","37,8","19,6","39,8","17,9","21,9","2,9"
28,2008,"57,5","37,9","19,6","39,7","17,8","21,9","2,8"
29,2009,"57,6","38,0","19,6","39,7","17,7","22,0","2,7"
30,2010,"57,7","38,0","19,7","39,7","17,6","22,1","2,6"
31,2011,"57,7","38,0","19,7","39,8","17,6","22,2","2,5"
32,2012,"57,7","38,0","19,7","39,8","17,5","22,3","2,5"
33,2013,"57,7","37,9","19,8","39,9","17,5","22,4","2,4"
34,2014,"57,6","37,8","19,8","40,0","17,5","22,5","2,4"
35,2015,"57,6","37,5","20,1","40,1","17,5","22,6","2,3"
36,2016,"57,6","37,3","20,3","40,1","17,5","22,6","2,3"
37,2017,"57,5","36,9","20,6","40,2","17,5","22,7","2,3"
38,2018,"57,5","36,7","20,8","40,3","17,6","22,7","2,2"
39,2019,"57,5","36,5","21,1","40,2","17,5","22,7","2,2"
40,2020,"57,5","36,2","21,3","40,3","17,6","22,7","2,2"
41,2021,"57,5","36,0","21,6","40,3","17,6","22,7","2,2"
42,2022,"57,5","35,7","21,8","40,3","17,6","22,7","2,2"
43,2023,"57,5","35,4","22,1","40,3","17,6","22,7","2,2"
44,2024,"57,4","35,1","22,3","40,3","17,6","22,7","2,2"
45,2025,"57,4","34,9","22,6","40,4","17,6","22,8","2,2"

In [ ]:
# Export

repartition_statut_occupation.to_csv("RepartitionStatutOccupation.csv", index = False)