In [7]:
import pandas as pd

logementsSociaux = pd.read_csv("C:/Users/gromm/Downloads/LogementsSociaux_France_et_Communes - Data.csv")
display(logementsSociaux)

,Observatoire des territoires - ANCT,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,Logements sociaux RPLS (Commune (2025)),NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,Nombre de logements sociaux (RPLS)
3,codgeo,libgeo,an,nb_rpls
4,01001,L'Abergement-Clémenciat,2023,22
...,...,...,...,...
34874,97613,M'Tsangamouji,NaN,NaN
34875,97614,Ouangani,2023,61
34876,97615,Pamandzi,2023,39
34877,97616,Sada,2023,6
34878,97617,Tsingoni,2023,193

In [ ]:
# Renamed columns

logementsSociaux.columns = ["code_geo", "lib_geo", "année", "nb_rpls"]

# Removed the 4 first rows of the data

logementsSociaux = logementsSociaux.drop(logementsSociaux.index[:4])
display(logementsSociaux)

      code_geo                  lib_geo année nb_rpls
4        01001  L'Abergement-Clémenciat  2023      22
5        01002    L'Abergement-de-Varey   NaN     NaN
6        01004        Ambérieu-en-Bugey  2023    2084
7        01005      Ambérieux-en-Dombes  2023     104
8        01006                  Ambléon   NaN     NaN
...        ...                      ...   ...     ...
34874    97613            M'Tsangamouji   NaN     NaN
34875    97614                 Ouangani  2023      61
34876    97615                 Pamandzi  2023      39
34877    97616                     Sada  2023       6
34878    97617                 Tsingoni  2023     193

[34875 rows x 4 columns]

In [ ]:
# Kept the departments from "Nord"

logementsSociaux = logementsSociaux[logementsSociaux['code_geo'].str.startswith('59')]
display(logementsSociaux)

      code_geo              lib_geo année nb_rpls
21751    59001            Abancourt   NaN     NaN
21752    59002               Abscon  2023     573
21753    59003                Aibes   NaN     NaN
21754    59004        Aix-en-Pévèle   NaN     NaN
21755    59005  Allennes-les-Marais  2023     135
...        ...                  ...   ...     ...
22393    59666         Zegerscappel  2023      30
22394    59667           Zermezeele   NaN     NaN
22395    59668            Zuydcoote  2023     115
22396    59669            Zuytpeene   NaN     NaN
22397    59670                  Don  2023      86

[647 rows x 4 columns]

In [ ]:
# Filled missing years

logementsSociaux['année'] = logementsSociaux["année"].fillna("2023")
display(logementsSociaux)

      code_geo              lib_geo année nb_rpls
21751    59001            Abancourt  2023     NaN
21752    59002               Abscon  2023     573
21753    59003                Aibes  2023     NaN
21754    59004        Aix-en-Pévèle  2023     NaN
21755    59005  Allennes-les-Marais  2023     135
...        ...                  ...   ...     ...
22393    59666         Zegerscappel  2023      30
22394    59667           Zermezeele  2023     NaN
22395    59668            Zuydcoote  2023     115
22396    59669            Zuytpeene  2023     NaN
22397    59670                  Don  2023      86

[647 rows x 4 columns]

In [ ]:
# Export

logementsSociaux.to_csv("LogementsSociaux.csv", index = False)