In [10]:
import pandas as pd

logements_insalubres = pd.read_csv("C:/Users/gromm/Downloads/LogementsInsalubres_France - LogementsInsalubres_France.csv")
display(logements_insalubres)

,Nombre de logements indignes et non décents,Libellé du type d'action,Libellé région,Code INSEE région,Libellé département,Code INSEE département,année d’entrée dans l’observatoire,mois d’entrée dans l’observatoire,jour d’entrée dans l’observatoire
0,1,Constat de non décence,AUVERGNE-RHONE-ALPES,84,AIN,1,2012.0,1.0,10/1/2012
1,1,Constat de non décence,AUVERGNE-RHONE-ALPES,84,AIN,1,2012.0,10.0,3/10/2012
2,1,Constat de non décence,AUVERGNE-RHONE-ALPES,84,AIN,1,2012.0,11.0,23/11/12
3,1,Constat de non décence,AUVERGNE-RHONE-ALPES,84,AIN,1,2013.0,2.0,1/2/2013
4,1,Constat de non décence,AUVERGNE-RHONE-ALPES,84,AIN,1,2013.0,7.0,1/7/2013
...,...,...,...,...,...,...,...,...,...
30668,4,Repérage suite réception d'un constat de risqu...,PROVENCE-ALPES-COTE D'AZUR,93,VAUCLUSE,84,2014.0,5.0,5/5/2014
30669,3,Repérage suite réception d'un constat de risqu...,PROVENCE-ALPES-COTE D'AZUR,93,VAUCLUSE,84,2014.0,9.0,11/9/2014
30670,3,Repérage suite réception d'un constat de risqu...,PROVENCE-ALPES-COTE D'AZUR,93,VAUCLUSE,84,2014.0,12.0,8/12/2014
30671,1,Repérage suite réception d'un constat de risqu...,PROVENCE-ALPES-COTE D'AZUR,93,VAUCLUSE,84,2015.0,4.0,9/4/2015
30672,1,Repérage suite réception d'un constat de risqu...,PROVENCE-ALPES-COTE D'AZUR,93,VAUCLUSE,84,2015.0,7.0,8/7/2015

In [ ]:
# Keep only rows where the department is "Nord"

logements_insalubres = logements_insalubres[logements_insalubres['Code INSEE département'].str.startswith('59')]
display(logements_insalubres)

,Nombre de logements indignes et non décents,Libellé du type d'action,Libellé région,Code INSEE région,Libellé département,Code INSEE département,année d’entrée dans l’observatoire,mois d’entrée dans l’observatoire,jour d’entrée dans l’observatoire
6387,1,Procédure de mise en sécurité des équipements ...,HAUTS-DE-FRANCE,32,NORD,59,2020.0,6.0,16/06/20
6949,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2015.0,1.0,28/01/15
6950,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2015.0,9.0,1/9/2015
6951,2,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2016.0,2.0,18/02/16
6952,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2016.0,3.0,4/3/2016
...,...,...,...,...,...,...,...,...,...
30363,34,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018.0,6.0,13/06/18
30364,1,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018.0,6.0,14/06/18
30365,6,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018.0,7.0,16/07/18
30366,3,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018.0,8.0,23/08/18
30367,1,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2019.0,3.0,21/03/19

In [ ]:
# Set the type of 2 rows from float to int because that didn't make sense

logements_insalubres['année d’entrée dans l’observatoire'] = logements_insalubres['année d’entrée dans l’observatoire'].astype(int)
logements_insalubres['mois d’entrée dans l’observatoire'] = logements_insalubres['mois d’entrée dans l’observatoire'].astype(int)
display(logements_insalubres)

,Nombre de logements indignes et non décents,Libellé du type d'action,Libellé région,Code INSEE région,Libellé département,Code INSEE département,année d’entrée dans l’observatoire,mois d’entrée dans l’observatoire,jour d’entrée dans l’observatoire
6387,1,Procédure de mise en sécurité des équipements ...,HAUTS-DE-FRANCE,32,NORD,59,2020,6,16/06/20
6949,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2015,1,28/01/15
6950,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2015,9,1/9/2015
6951,2,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2016,2,18/02/16
6952,1,Procédure de péril,HAUTS-DE-FRANCE,32,NORD,59,2016,3,4/3/2016
...,...,...,...,...,...,...,...,...,...
30363,34,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018,6,13/06/18
30364,1,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018,6,14/06/18
30365,6,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018,7,16/07/18
30366,3,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2018,8,23/08/18
30367,1,Repérage suite réception d'un constat de risqu...,HAUTS-DE-FRANCE,32,NORD,59,2019,3,21/03/19

In [ ]:
# Export

logements_insalubres.to_csv("LogementsInsalubres.csv", index = False)