In [6]:
import pandas as pd

evol_nb_logements = pd.read_csv("C:/Users/gromm/Downloads/Parc de logements.xlsx - Figure 2.csv")
display(evol_nb_logements)

,Figure 2 – Évolution du nombre de logements selon la catégorie et de la population,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,indice base 100 en 1982
1,Année,Ensemble des logements,Résidences principales,Résidences secondaires et logements occasionnels,Logements vacants,Population
2,1982,"100,0","100,0","100,0","100,0","100,0"
3,1983,"101,5","101,4","103,1","100,4","100,6"
4,1984,"103,1","102,9","106,4","100,9","101,1"
5,1985,"104,6","104,3","109,5","101,3","101,6"
6,1986,"106,0","105,6","112,6","101,6","102,1"
7,1987,"107,3","106,9","115,8","101,8","102,6"
8,1988,"108,6","108,1","118,6","101,9","103,2"
9,1989,"109,8","109,2","121,4","101,9","103,8"
10,1990,"111,0","110,3","124,2","101,9","104,4"
11,1991,"112,3","111,8","124,9","102,7","104,9"
12,1992,"113,5","113,1","125,3","103,5","105,4"
13,1993,"114,7","114,4","125,8","104,2","105,9"
14,1994,"115,9","115,7","126,2","104,9","106,3"
15,1995,"117,1","117,1","126,7","105,7","106,7"
16,1996,"118,3","118,5","127,1","106,4","107,0"
17,1997,"119,5","119,8","127,5","107,0","107,4"
18,1998,"120,7","121,1","127,8","107,7","107,8"
19,1999r,"121,8","122,6","128,2","106,0","108,2"
20,2000r,"123,3","124,3","128,9","105,8","108,9"
21,2001r,"124,8","126,0","129,7","105,6","109,7"
22,2002r,"126,2","127,8","130,4","104,4","110,5"
23,2003r,"127,7","129,6","131,3","103,2","111,3"
24,2004r,"129,2","131,3","132,5","103,0","112,0"
25,2005r,"130,7","133,0","133,8","102,7","112,9"
26,2006r,"132,3","134,6","135,6","104,3","113,7"
27,2007r,"134,0","136,2","136,4","107,7","114,5"
28,2008r,"135,6","137,6","137,2","112,6","115,1"
29,2009r,"137,2","139,0","137,3","118,3","115,7"
30,2010r,"138,7","140,2","137,8","123,5","116,3"
31,2011r,"140,2","141,5","138,6","127,9","116,8"
32,2012r,"141,7","142,7","140,3","133,1","117,4"
33,2013r,"143,3","143,9","141,9","138,1","118,0"
34,2014r,"144,9","145,2","144,3","142,3","118,6"
35,2015r,"146,5","146,4","146,9","146,3","119,1"
36,2016r,"147,9","147,6","149,5","149,8","119,4"
37,2017r,"149,4","148,8","152,1","152,1","119,7"
38,2018r,"150,8","150,2","154,2","153,1","120,1"
39,2019r,"152,2","151,5","155,6","155,5","120,5"
40,2020r,"153,6","152,9","157,4","156,2","120,9"
41,2021r,"154,8","154,2","159,0","156,5","121,3"
42,2022r,"156,2","155,7","160,2","156,0","121,9"
43,2023p,"157,5","157,1","161,8","156,2","122,3"
44,2024p,"158,8","158,5","163,3","156,3","122,6"
45,2025p,"160,0","159,8","164,7","156,3","122,9"
46,p : données provisoires ; r : données révisées.,NaN,NaN,NaN,NaN,NaN
47,"Lecture : Entre 1982 et 2025, le nombre de log...",NaN,NaN,NaN,NaN,NaN
48,Champ : France hors Mayotte.,NaN,NaN,NaN,NaN,NaN
49,"Sources : Insee, estimations de population ; m...",NaN,NaN,NaN,NaN,NaN

In [ ]:
# Renamed columns

evol_nb_logements.columns = ["annee", "ensemble_logements", "residences_principales", "residences_secondaires", "logement_vacants", "population"]

# Removed the 4 last and the 2 first rows because they were describing what the data does but wasn't actionnable

evol_nb_logements = evol_nb_logements.drop(evol_nb_logements.index[-4:])
evol_nb_logements = evol_nb_logements.drop(evol_nb_logements.index[:2])

display(evol_nb_logements)

,annee,ensemble_logements,residences_principales,residences_secondaires,logement_vacants,population
2,1982,"100,0","100,0","100,0","100,0","100,0"
3,1983,"101,5","101,4","103,1","100,4","100,6"
4,1984,"103,1","102,9","106,4","100,9","101,1"
5,1985,"104,6","104,3","109,5","101,3","101,6"
6,1986,"106,0","105,6","112,6","101,6","102,1"
7,1987,"107,3","106,9","115,8","101,8","102,6"
8,1988,"108,6","108,1","118,6","101,9","103,2"
9,1989,"109,8","109,2","121,4","101,9","103,8"
10,1990,"111,0","110,3","124,2","101,9","104,4"
11,1991,"112,3","111,8","124,9","102,7","104,9"
12,1992,"113,5","113,1","125,3","103,5","105,4"
13,1993,"114,7","114,4","125,8","104,2","105,9"
14,1994,"115,9","115,7","126,2","104,9","106,3"
15,1995,"117,1","117,1","126,7","105,7","106,7"
16,1996,"118,3","118,5","127,1","106,4","107,0"
17,1997,"119,5","119,8","127,5","107,0","107,4"
18,1998,"120,7","121,1","127,8","107,7","107,8"
19,1999r,"121,8","122,6","128,2","106,0","108,2"
20,2000r,"123,3","124,3","128,9","105,8","108,9"
21,2001r,"124,8","126,0","129,7","105,6","109,7"
22,2002r,"126,2","127,8","130,4","104,4","110,5"
23,2003r,"127,7","129,6","131,3","103,2","111,3"
24,2004r,"129,2","131,3","132,5","103,0","112,0"
25,2005r,"130,7","133,0","133,8","102,7","112,9"
26,2006r,"132,3","134,6","135,6","104,3","113,7"
27,2007r,"134,0","136,2","136,4","107,7","114,5"
28,2008r,"135,6","137,6","137,2","112,6","115,1"
29,2009r,"137,2","139,0","137,3","118,3","115,7"
30,2010r,"138,7","140,2","137,8","123,5","116,3"
31,2011r,"140,2","141,5","138,6","127,9","116,8"
32,2012r,"141,7","142,7","140,3","133,1","117,4"
33,2013r,"143,3","143,9","141,9","138,1","118,0"
34,2014r,"144,9","145,2","144,3","142,3","118,6"
35,2015r,"146,5","146,4","146,9","146,3","119,1"
36,2016r,"147,9","147,6","149,5","149,8","119,4"
37,2017r,"149,4","148,8","152,1","152,1","119,7"
38,2018r,"150,8","150,2","154,2","153,1","120,1"
39,2019r,"152,2","151,5","155,6","155,5","120,5"
40,2020r,"153,6","152,9","157,4","156,2","120,9"
41,2021r,"154,8","154,2","159,0","156,5","121,3"
42,2022r,"156,2","155,7","160,2","156,0","121,9"
43,2023p,"157,5","157,1","161,8","156,2","122,3"
44,2024p,"158,8","158,5","163,3","156,3","122,6"
45,2025p,"160,0","159,8","164,7","156,3","122,9"

In [ ]:
# Removed the "r" and the "p" on years

evol_nb_logements["annee"] = evol_nb_logements["annee"].str.replace("r", '')
evol_nb_logements["annee"] = evol_nb_logements["annee"].str.replace("p", '')
display(evol_nb_logements)

,annee,ensemble_logements,residences_principales,residences_secondaires,logement_vacants,population
2,1982,"100,0","100,0","100,0","100,0","100,0"
3,1983,"101,5","101,4","103,1","100,4","100,6"
4,1984,"103,1","102,9","106,4","100,9","101,1"
5,1985,"104,6","104,3","109,5","101,3","101,6"
6,1986,"106,0","105,6","112,6","101,6","102,1"
7,1987,"107,3","106,9","115,8","101,8","102,6"
8,1988,"108,6","108,1","118,6","101,9","103,2"
9,1989,"109,8","109,2","121,4","101,9","103,8"
10,1990,"111,0","110,3","124,2","101,9","104,4"
11,1991,"112,3","111,8","124,9","102,7","104,9"
12,1992,"113,5","113,1","125,3","103,5","105,4"
13,1993,"114,7","114,4","125,8","104,2","105,9"
14,1994,"115,9","115,7","126,2","104,9","106,3"
15,1995,"117,1","117,1","126,7","105,7","106,7"
16,1996,"118,3","118,5","127,1","106,4","107,0"
17,1997,"119,5","119,8","127,5","107,0","107,4"
18,1998,"120,7","121,1","127,8","107,7","107,8"
19,1999,"121,8","122,6","128,2","106,0","108,2"
20,2000,"123,3","124,3","128,9","105,8","108,9"
21,2001,"124,8","126,0","129,7","105,6","109,7"
22,2002,"126,2","127,8","130,4","104,4","110,5"
23,2003,"127,7","129,6","131,3","103,2","111,3"
24,2004,"129,2","131,3","132,5","103,0","112,0"
25,2005,"130,7","133,0","133,8","102,7","112,9"
26,2006,"132,3","134,6","135,6","104,3","113,7"
27,2007,"134,0","136,2","136,4","107,7","114,5"
28,2008,"135,6","137,6","137,2","112,6","115,1"
29,2009,"137,2","139,0","137,3","118,3","115,7"
30,2010,"138,7","140,2","137,8","123,5","116,3"
31,2011,"140,2","141,5","138,6","127,9","116,8"
32,2012,"141,7","142,7","140,3","133,1","117,4"
33,2013,"143,3","143,9","141,9","138,1","118,0"
34,2014,"144,9","145,2","144,3","142,3","118,6"
35,2015,"146,5","146,4","146,9","146,3","119,1"
36,2016,"147,9","147,6","149,5","149,8","119,4"
37,2017,"149,4","148,8","152,1","152,1","119,7"
38,2018,"150,8","150,2","154,2","153,1","120,1"
39,2019,"152,2","151,5","155,6","155,5","120,5"
40,2020,"153,6","152,9","157,4","156,2","120,9"
41,2021,"154,8","154,2","159,0","156,5","121,3"
42,2022,"156,2","155,7","160,2","156,0","121,9"
43,2023,"157,5","157,1","161,8","156,2","122,3"
44,2024,"158,8","158,5","163,3","156,3","122,6"
45,2025,"160,0","159,8","164,7","156,3","122,9"

In [ ]:
# Export

evol_nb_logements.to_csv("EvolutionNombreLogements.csv", index = False)