In [52]:
%pip install pandas
%pip install openpyxl

Requirement already satisfied: pandas in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\gromm\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\gromm\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\gromm\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\gromm\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\gromm\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [53]:
import pandas as pd

mal_logement = pd.read_excel("C:/Users/gromm/Downloads/MalLogementFrance.xlsx")

In [54]:
display(mal_logement)

                                      Habitat dégradé  2 202 000
0                            Logements inconfortables  1 874 000
1    Gens du voyage en mauvaises conditions d'habitat    208 000
2          Habitat de fortune (camping, cabane, etc.)    100 000
3            Foyers de travailleurs migrants dégradés     20 000
4                 2- Logements exigus (surpeuplement)  1 128 000
5                    3- Absence de logement personnel  1 018 000
6                 Hébergement contraint chez un tiers    643 000
7   Sans domicile (sans-abri, hébergement d'urgenc...    350 000
8                      Résidence permanente à l'hôtel     25 000
9                     4- Personnes comptées deux fois  - 175 000
10                                           Ensemble  4 173 000

In [ ]:
# Renamed columns

mal_logement.columns = ["logement_type", "nb_of_people"]
display(mal_logement)

                                        logement_type nb_of_people
0                            Logements inconfortables    1 874 000
1    Gens du voyage en mauvaises conditions d'habitat      208 000
2          Habitat de fortune (camping, cabane, etc.)      100 000
3            Foyers de travailleurs migrants dégradés       20 000
4                 2- Logements exigus (surpeuplement)    1 128 000
5                    3- Absence de logement personnel    1 018 000
6                 Hébergement contraint chez un tiers      643 000
7   Sans domicile (sans-abri, hébergement d'urgenc...      350 000
8                      Résidence permanente à l'hôtel       25 000
9                     4- Personnes comptées deux fois    - 175 000
10                                           Ensemble    4 173 000

In [ ]:
# Removed white spaces from data

mal_logement["nb_of_people"].replace(' ', '')

0     1 874 000
1       208 000
2       100 000
3        20 000
4     1 128 000
5     1 018 000
6       643 000
7       350 000
8        25 000
9     - 175 000
10    4 173 000
Name: nb_of_people, dtype: str

In [ ]:
# Export

mal_logement.to_csv("MalLogementFrance.csv")