In [4]:
import pandas as pd

locatairesUE_2018 = pd.read_csv("C:/Users/gromm/Downloads/Proprio_VS_Locataires_LocatairesUE_2018.csv")
display(locatairesUE_2018)

                         Locataires dans l'UE en 2018             Unnamed: 1
0                                                 NaN                    NaN
1                                                 NaN  en % de la population
2                                                 NaN             Locataires
3                                           Allemagne                   48.5
4                                            Autriche                   44.6
5                                            Danemark                   39.5
6                                               Suède                   35.9
7                                        Royaume-Uni1                   34.9
8                                              France                   34.9
9                                            Pays-Bas                   31.1
10                                                 UE                   30.7
11                                             Chypre                   29.9
12                                           Irlande1                   29.7
13                                         Luxembourg                   28.8
14                                           Finlande                   28.4
15                                             Italie                   27.6
16                                           Belgique                   27.3
17                                              Grèce                   26.5
18                                           Portugal                   25.5
19                                           Slovénie                   24.9
20                                            Espagne                   23.7
21                                       Rép. tchèque                   21.3
22                                           Lettonie                   18.4
23                                              Malte                   18.4
24                                            Estonie                   17.6
25                                           Bulgarie                   16.4
26                                            Pologne                   16.0
27                                            Hongrie                   14.0
28                                           Lituanie                   10.1
29                                            Croatie                    9.9
30                                          Slovaquie                    8.7
31                                           Roumanie                    3.6
32                            1. Données provisoires.                    NaN
33  Source : Eurostat (extraction du 17 décembre 2...                    NaN

In [ ]:
# Renamed columns 

locatairesUE_2018.columns = ["pays", "pourcent_locataires"]

# Removed the 3 first and 2 last useless rows because they were just describing what the data stands for but isn't actionnable for us

locatairesUE_2018 = locatairesUE_2018.drop(locatairesUE_2018.index[:3])
locatairesUE_2018 = locatairesUE_2018.drop(locatairesUE_2018.index[-2:])

display(locatairesUE_2018)

            pays pourcent_locataires
3      Allemagne                48.5
4       Autriche                44.6
5       Danemark                39.5
6          Suède                35.9
7   Royaume-Uni1                34.9
8         France                34.9
9       Pays-Bas                31.1
10            UE                30.7
11        Chypre                29.9
12      Irlande1                29.7
13    Luxembourg                28.8
14      Finlande                28.4
15        Italie                27.6
16      Belgique                27.3
17         Grèce                26.5
18      Portugal                25.5
19      Slovénie                24.9
20       Espagne                23.7
21  Rép. tchèque                21.3
22      Lettonie                18.4
23         Malte                18.4
24       Estonie                17.6
25      Bulgarie                16.4
26       Pologne                16.0
27       Hongrie                14.0
28      Lituanie                10.1
29       Croatie                 9.9
30     Slovaquie                 8.7
31      Roumanie                 3.6

In [ ]:
# Export

locatairesUE_2018.to_csv("LocatairesUE_2018.csv", index = False)